### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method

### ISSUE THREAD

**Issue by bala-drg** [mhart/aws4#100] opened 2019-10-10 04:46 UTC
i'm getting AWS signature  mismatch when i send request to API Gateway using axios

```javascript
let data = JSON.stringify({
    "action": "message",
    "data": 'testing'
  })


let request = {
  host: '<API GATEWAY ID>.execute-api.<AWS REGION>.amazonaws.com',
  url: 'https://<API GATEWAY ID>.execute-api.<AWS REGION>.amazonaws.com/dev/@connections/<CONNECTION ID>',
  path: 'dev/@connections/<CONNECTION ID>',
  service: 'execute-api',
  region: '<AWS REGION>',
  data: data,
  body: data,
  headers: {
    'Content-Type': 'application/json'
  }
}

let signedRequest = aws4.sign(request,
                {
                  secretAccessKey: '<AWS SECRET KEY>',
                  accessKeyId: '<AWS ACCESS KEY>'
                })

let response = axios(signedRequest)
```

**Comment by MythologicalEngineer** [comment] 2019-10-24 16:55
@bala-drg Did you find any resolution to this? I'm having the same issue and it seems to have happened quite suddenly.

**Comment by MythologicalEngineer** [comment] 2019-11-27 15:48
I found a fix that worked for me. You have to add body to the request and make it a string of the data object.

example:
request.body = JSON.stringify(request.data);

Put that before the aws4.sign method and it works. The problem is due to how Axios uses data rather than body.

**Comment by mhart** [comment] 2020-05-11 17:47
Closing as an issue with axios, not this library

**Closed by mhart** 2020-05-11 17:47 UTC
