### ISSUE TITLE
Breaking change in handling of headers in `1.13.0`

### ISSUE THREAD

**Issue by eyalroth** [mhart/aws4#175] opened 2024-12-01 16:27 UTC
The change in https://github.com/mhart/aws4/commit/8442685a82a877891be5b6c7e9e6d0e53b637705 (following #164) introduces a breaking change.

```ts
const headers = { foo: '1' };
const request = { headers };
aws4.sign(request, credentials);

// before the change, this would mutate the headers on the request, now it doesn't
headers['bar'] = '2';
```

This isn't necessarily a "legitimate" use case, but the change to the package may silently break existing code (especially since the change is labeled as minor).

**Comment by mhart** [comment] 2024-12-01 20:55
This has been discussed in #164 and #165 – have a read through those issues for background.

Mutating headers was never part of the public API (and never documented). What were you relying on this for?

**Comment by mhart** [comment] 2024-12-01 20:59
Closing as a duplicate of #165

**Closed as completed by mhart** 2024-12-01 20:59 UTC

**Comment by eyalroth** [comment] 2024-12-05 11:59
> Mutating headers was never part of the public API (and never documented).

@mhart What public API? it's a plain JSON. No one expects a third-party function to replace the reference of properties in a JSON if it doesn't document it.

> What were you relying on this for?

Tests broke due to Jest spy. It's not necessarily a production issue, but it might be.

The point is not that this change is not good, but that it should be marked as major, as it breaks existing behavior in unexpected ways.

**Comment by mhart** [comment] 2024-12-05 22:11
> What public API?

The documented API in the README. All libraries have an API. The term "API" in software refers to any programming interface. The interface to a software library is one type of API.

With semver, you create a new major whenever you make breaking changes to your public API. You can read up more here: https://semver.org/
